"""add_user_role

Revision ID: aad2a7ea84aa
Revises: 63e14f16dd1f
Create Date: 2023-10-08 21:00:55.723925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad2a7ea84aa'
down_revision: Union[str, None] = '63e14f16dd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE TYPE role AS ENUM ('client', 'agent', 'moderator', 'admin');"))
    op.add_column('users', sa.Column('role', sa.Enum('client', 'agent', 'moderator', 'admin', name='role'), server_default='client', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
